#!/usr/bin/env node
/**
 * RAJLI CAR RENTAL — fleet auto-discovery
 *
 * Scans every folder in the project root (excluding `assets/` and hidden
 * folders) and writes `cars.json` for the static site to consume.
 *
 * Each car folder is expected to contain:
 *   - <something>main.<ext>   → main display image
 *   - Gallery/                → folder of additional photos
 *   - description.txt         → free-form text (parsed for Name/Year/...)
 *
 * Re-run after adding / renaming / removing a car folder:
 *   node generate-cars.js
 */
const fs = require("fs");
const path = require("path");

const ROOT = __dirname;
const IMG_EXT = new Set([".jpg", ".jpeg", ".png", ".webp", ".gif", ".avif"]);
const EXCLUDE = new Set(["assets", "node_modules"]);

function isImage(file) {
  return IMG_EXT.has(path.extname(file).toLowerCase());
}

function grab(label, text) {
  const re = new RegExp(`${label}\\s*:?\\s*(.+)`, "i");
  const m = text.match(re);
  return m ? m[1].trim() : "";
}

/**
 * Sort an image list so the smallest, web-optimised version wins.
 * Order of preference:
 *   1. lowercase .jpg / .webp / .avif  (web-compressed)
 *   2. anything else (.PNG, .JPG, .jpeg originals)
 */
function preferWeb(a, b) {
  const score = (f) => {
    const ext = path.extname(f).toLowerCase();
    if (ext === ".webp" || ext === ".avif") return 0;
    if (ext === ".jpg") return 1;
    if (ext === ".jpeg") return 2;
    if (ext === ".png") return 3;
    return 4;
  };
  return (
    score(a) - score(b) ||
    a.length - b.length ||           // shorter filename wins (avoids picking up *.compressed.jpg test artifacts)
    a.localeCompare(b)
  );
}

/**
 * De-duplicate gallery files that share a basename but differ in extension
 * (e.g. IMG_4501.jpeg + IMG_4501.jpg both exist after compression).
 * Keeps the most web-friendly one.
 */
function dedupByBasename(files) {
  const groups = new Map();
  files.forEach((f) => {
    const key = path.basename(f, path.extname(f)).toLowerCase();
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key).push(f);
  });
  return [...groups.values()].map((g) => g.sort(preferWeb)[0]);
}

function readCar(folder) {
  const full = path.join(ROOT, folder);
  const files = fs.readdirSync(full).filter((f) => !f.startsWith("."));

  // main image: any image file with "main" in its name. Prefer the
  // web-compressed copy (lowercase .jpg) over the original (.PNG/.jpeg).
  const mains = files
    .filter((f) => isImage(f) && f.toLowerCase().includes("main"))
    .sort(preferWeb);
  const main = mains[0] || files.find(isImage) || null;

  // gallery
  const galleryDir = path.join(full, "Gallery");
  let gallery = [];
  if (fs.existsSync(galleryDir) && fs.statSync(galleryDir).isDirectory()) {
    const all = fs
      .readdirSync(galleryDir)
      .filter((f) => !f.startsWith(".") && isImage(f));
    gallery = dedupByBasename(all).sort();
  }

  // description
  let description = "";
  const descPath = path.join(full, "description.txt");
  if (fs.existsSync(descPath)) {
    description = fs.readFileSync(descPath, "utf-8").trim();
  }

  const name = grab("Name", description) || folder;
  const year = grab("Year", description);
  const transmission = grab("Transmission", description);
  const engine = grab("Engine", description);

  // append year from folder name if name doesn't already include it
  const folderYear = folder.match(/(20\d{2})/);
  const displayName =
    folderYear && !name.includes(folderYear[1])
      ? `${name} ${folderYear[1]}`
      : name;

  return {
    id: folder,
    folder,
    displayName: displayName.trim(),
    name: name.trim(),
    year,
    transmission,
    engine,
    main,
    gallery,
    description,
  };
}

function main() {
  const entries = fs
    .readdirSync(ROOT)
    .filter((f) => !f.startsWith(".") && !EXCLUDE.has(f))
    .filter((f) => fs.statSync(path.join(ROOT, f)).isDirectory())
    .sort();

  const cars = entries.map(readCar);
  fs.writeFileSync(
    path.join(ROOT, "cars.json"),
    JSON.stringify(cars, null, 2),
    "utf-8"
  );
  // Also emit a plain JS file that defines a global, so the site works
  // when opened directly from the filesystem (file:// blocks fetch).
  const jsBody = `/* AUTO-GENERATED by generate-cars.js — do not edit */\nwindow.__RAJLI_CARS__ = ${JSON.stringify(
    cars,
    null,
    2
  )};\n`;
  fs.writeFileSync(path.join(ROOT, "cars-data.js"), jsBody, "utf-8");

  console.log(`wrote ${cars.length} cars to cars.json + cars-data.js`);
  cars.forEach((c) =>
    console.log(`  • ${c.displayName.padEnd(28)} main=${c.main || "MISSING"}  gallery=${c.gallery.length}`)
  );
}

main();
